appointment_manager_config:
  path: /appointmentmanager/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\AppointmentManagerConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerConfigurationController'

appointment_manager_customerlist:
  path: /appointmentmanager/customerlist
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\CustomerListController::index'
    # Needed to work with tab system
    _legacy_controller: 'CustomerListController'