appointment_manager_config:
  path: /appointmentmanager/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\AppointmentManagerConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerConfigurationController'

appointment_manager_appointment_list:
  path: /appointmentmanager/appointmentlist
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\AppointmentManagerAppointmentListController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerAppointmentListController'

admin_appointment_manager_itinerary:
  path: /appointmentmanager/itinerary
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\AppointmentManagerItineraryController::index'

# Route pour la page du formulaire front-office
appointment_manager_form:
    path: /rendez-vous
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\AppointmentManager\Controller\Front\AppointmentManagerAppointmentFrontController::index'
        _legacy_controller: 'AppointmentManagerAppointmentFront'