appointment_manager_config:
  path: /appointmentmanager/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\AppointmentManagerConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerConfigurationController'

appointment_manager_appointment_list:
  path: /appointmentmanager/appointmentlist
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\AppointmentManagerAppointmentListController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerAppointmentListController'

admin_appointment_manager_itinerary:
  path: /appointmentmanager/itinerary
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\AppointmentManagerItineraryController::index'

appointment_front_form:
  path: /appointmentmanager/form
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Front\AppointmentManagerAppointmentFrontController::index'

appointment_invite:
  path: /appointment/invite
  methods: [GET]
  defaults:
    _controller: 'Modules\AppointmentManager\Controller\Front\AppointmentManagerInviteController::index'