appointment_manager_config:
  path: /appointmentmanager/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\AppointmentManagerConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerConfigurationController'
    _legacy_link: 'AppointmentManagerConfiguration'

appointment_manager_appointment_list:
  path: /appointmentmanager/appointmentlist
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\AppointmentManagerAppointmentListController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerAppointmentListController'
    _legacy_link: 'AppointmentManagerAppointmentList'

admin_appointment_manager_itinerary:
  path: /appointmentmanager/itinerary
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\AppointmentManager\Controller\Admin\AppointmentManagerItineraryController::index'
    # Needed to work with tab system
    _legacy_controller: 'AppointmentManagerItineraryController'
    _legacy_link: 'AppointmentManagerItinerary'