services:
  _defaults:
    public: true

  # Appointment Manager configuration form
  prestashop.module.appointmentmanager.form.appointmentmanager_config_form_type:
    class: 'PrestaShop\Module\AppointmentManager\Form\AppointmentManagerConfigFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.appointmentmanager.form.appointmentmanager_data_config:
    class: 'PrestaShop\Module\AppointmentManager\Form\AppointmentManagerDataConfig'
    arguments: ['@prestashop.adapter.legacy.configuration']

  prestashop.module.appointmentmanager.form.appointmentmanager_data_provider:
    class: 'PrestaShop\Module\AppointmentManager\Form\AppointmentManagerDataProvider'
    arguments:
      - '@prestashop.module.appointmentmanager.form.appointmentmanager_data_config'

  prestashop.module.appointmentmanager.form.appointmentmanager_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.appointmentmanager.form.appointmentmanager_data_provider'
      - 'PrestaShop\Module\AppointmentManager\Form\AppointmentManagerConfigFormType'
      - 'AppointmentManagerConfig'

 # Your new services
  PrestaShop\Module\AppointmentManager\Service\ItineraryService: ~

  PrestaShop\Module\AppointmentManager\Admin\AppointmentManagerItineraryController:
    public: true
    arguments:
      - '@PrestaShop\Module\AppointmentManager\Service\ItineraryService'
      - '%appointmentManager.google_api_key%'

  # PrestaShop\Module\AppointmentManager\Admin\AppointmentManagerConfigurationController:
  #   public: true

  # PrestaShop\Module\AppointmentManager\Admin\AppointmentManagerAppointmentListController:
  #   public: true

parameters:
  appointmentManager.google_api_key: '%env(APPOINTMENTMANAGER_GOOGLE_API_KEY)%'